version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 7.0

  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore weathertest/weathertest.csproj

  build:
    commands:
      - echo Build started on `date`
      - dotnet build weathertest/weathertest.csproj

  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release -o ./ weathertest/weathertest.csproj

artifacts:
  files:
    - '**/*'
